### ISSUE TITLE
Pulling service writes a stellate.ts file instead of stellate.yml in the latest release

### ISSUE THREAD

**Issue by kareemgr** [StellateHQ/cli#3]
Running `stellate pull` is writing a `stellate.ts` file instead of  `stellate.yml`.

**To Reproduce**
1. Install latest stellate CLI version.
2. Run `npx stellate pull --service {serviceName}`
3. `stellate.ts` file is created.

**Expected behavior**
A `stellate.yml` file should be created.

Thank you!

**Comment by JoviDeCroock** [comment]
Hey,

This is expected we are transitioning to a code-based config, if we see a `tsconfig` file we will write a `stellate.ts` file instead which will offer you auto-completion/...

**Comment by kareemgr** [comment]
Is there a way to force pulling `yaml` format at the moment ?

**Comment by JoviDeCroock** [comment]
Not at the moment, I can propose this to the team. Any reason why you prefer `yaml`? You can most likely force yaml by making an existing yaml config `stellate.yml` and calling `pull`

**Comment by kareemgr** [comment]
Alright, thanks for the hack! 👍 

We use `stellate.yml` in CI along with other tools to validate & deploy service configurations.

Another thing that would be awesome to have, is the ability to specify the filename e.g. `stellate pull --service {env} -o current-stellate.yml`

**Comment by zcei** [comment]
Hej @kareemgr, thanks for your feedback! 

I incorporated a new `--output-format` into `stellate@1.15.0`. With this you should be able to run `stellate pull --output-format yml` and you can avoid the workaround from @JoviDeCroock.

(Heads up: If it detects an existing config in a different format you'll see a warning)

Regarding the option to specify a different file name: as our CLI wouldn't account for that in any other command, we don't plan to support this option in the near future. I would recommend a manual `mv stellate.yml current-stellate.yml` after pulling.
